# Generated by Django 6.0 on 2026-04-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carmodel_delete_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('fuel', 'Fuel'), ('electric', 'Electric')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='max_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(blank=True, choices=[('auto', 'automatic'), ('manual', 'Manual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.brandmodel'),
        ),
    ]
