# Generated by Django 6.0 on 2026-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_brandmodel_remove_carmodel_price_carmodel_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='available',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
