# Generated by Django 6.0 on 2026-04-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_carmodel_available_carmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='Brand_name',
            new_name='brand',
        ),
    ]
