# Generated by Django 6.0 on 2026-04-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_rename_brand_name_brandmodel_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='brand',
            new_name='name',
        ),
    ]
