# Generated by Django 6.0 on 2026-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_location_address_location_extra_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='Unknown address'),
        ),
    ]
