# Generated by Django 6.0 on 2026-05-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.location'),
        ),
    ]
