# Generated by Django 6.0 on 2026-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshot/'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='method',
            field=models.CharField(choices=[('kbz', 'KBZ Pay'), ('wave', 'Wave Pay'), ('uab', 'UAB Pay'), ('aya', 'AYA Pay')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
